### ISSUE TITLE
frida-gum-devkit-xxx-android-arm: requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC

### ISSUE THREAD

**Issue by jrd-rocks** [frida/frida-gum#299]
This seems to be a similar issue as / regression of https://github.com/frida/frida-gum/issues/244

When trying to use https://github.com/frida/frida/releases/download/12.2.1/frida-gum-devkit-12.2.1-android-arm.tar.xz i get the linking error `requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC`

Since in issue https://github.com/frida/frida-gum/issues/244 it was mentioned there were no issues for android-arm, so i tried that one (frida-gum-devkit-10.6.24-android-arm). It worked.

I'm completely clueless how to build frida-gum myself, so kinda depending on the available devkit.

**Comment by oleavr** [comment]
The code was built with `-fPIC` so that error isn't correct, or there's a bug in the NDK toolchain. Anyway, you should be linking with `-Wl,--gc-sections`, which both gives you smaller binaries and avoids this issue (because the faulty symbols aren't actually used). You probably also want some of the other Android linker flags from `releng/setup-env.sh`: `-Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -fuse-ld=gold -Wl,--fix-cortex-a8 -Wl,--icf=safe`

**Comment by jrd-rocks** [comment]
Thanks, that workaround (-Wl,-Bsymbolic) helped!
