### ISSUE TITLE
Frida crashing with: Blob indicates that message exceeds maximum message length

### ISSUE THREAD

**Issue by bannsec** [frida/frida-gum#370]
In messing around with Windows' calculator.exe, Frida crashes with the following error:

```
(frida:20628): GLib-GIO-WARNING **: 11:03:11.848: _g_dbus_worker_do_read_cb: error determining bytes needed: Blob indicates that message exceeds maximum message length (128MiB)
```

Setup is effectively:
 - Run calc.exe (outside of Frida)
 - Frida attach to calculator.exe
 - Frida start stalking on call and ret events
 - Press a few buttons in the calculator
 - Couple hundred thousand events come in successfully
 - Then crash

This appears to be related to #368 . Basically, if I don't drastically increase the stalker send buffer, then I run out of buffer and stop receiving input from tracing on linux. However, if I do increase that buffer, then Windows gets upset about the buffer being too large or something.

**Comment by oleavr** [comment]
This is unfortunately the expected behavior – though it is a usability bug (PRs welcome). The issue here is that `send()` leaves it up to you to implement chunking/batching/back pressure/etc. There isn't "one true way" here as some applications will want to optimize for latency whereas others will want to optimize for throughput – potentially even for their particular use-case.

For an off-the-shelf module that implements a solution for bulk transfer use-cases, like memory dumping, check out:
https://github.com/nowsecure/frida-remote-stream
This isn't super-helpful for your use-case though as the host-side code is for Node.js – so you would have to reimplement those bits in Python.

**Comment by ser1-lgtm** [comment]
While running fridump I am getting the error (frida:45591): GLib-GIO-WARNING **: 15:55:41.905: _g_dbus_worker_do_read_cb: error determining bytes needed: Blob indicates that message exceeds maximum message length (128MiB)
