### ISSUE TITLE
enhancement - iOS ARM64 ABI for variadic functions

### ISSUE THREAD

**Issue by jkl-caliber** [frida/frida-gum#439]
On iOS ARM64, variadic parameters are passed on the stack.

https://developer.apple.com/library/archive/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html

The Frida documentation lists no option for using the iOS ARM64 ABI. The default ABI uses registers.

https://frida.re/docs/javascript-api/#nativefunction

A workaround is to use dummy parameters for the registers.

**Comment by oleavr** [comment]
Frida's `NativeFunction` implementation uses the default C ABI by default. This is implemented by libffi under the hood. So if you find a mismatch it means it's a bug in libffi, and we'd appreciate pull-requests at:
https://github.com/frida/libffi
(I can help submit them upstream afterwards.)

**Comment by oleavr** [comment]
By the way, when defining your `NativeFunction` make sure you include the variadic marker between your function's *fixed* arguments and its *variadic* arguments. E.g. `['pointer', '...', 'int']` if a function has the following signature `char *, ...` and you want to call it with `char *, int`.

**Comment by jkl-caliber** [comment]
The ABI comes into play both when calling a NativeFunction and when using Interceptor.attach to observe the function being called. I think libffi handles the former case and the gum interceptor code handles the latter.

**Comment by oleavr** [comment]
Yes, I actually [fixed](https://github.com/libffi/libffi/commit/419503f409c321fe31ff59d963ef34bb913420d0) libffi's varargs-handling on iOS, as the ABI is slightly different than the SysV one.

However, Interceptor doesn't know anything about the actual function signature (by design), and the `args` object is just a virtual array with an infinite number of elements, which only works for the simple cases. (Where arguments are simple and allocated according to the platform's default C ABI without varargs etc.) So for everything else one has to access registers and memory manually.

**Comment by oleavr** [comment]
> So for everything else one has to access registers and memory manually.

Or use `Interceptor.replace()` with `NativeCallback`, which means libffi will do the heavy lifting for you.
