### ISSUE TITLE
build receipes

### ISSUE THREAD

**Issue by vanhauser-thc** [frida/frida-gum#470]
I am trying to build frida-gum for aarch64 non-android Linux but failing.
Can you please make the intel_x64 Linux receipe public, e.g. putting it into a README/HOWTO?
thank you!

**Comment by vanhauser-thc** [comment]
@oleavr & @WorksButNotTested 
can one of you please supply that intel_x64 build receipe? It is just a simple copy+paste for you and for me it helps me as I am stuck :)
thank you!

**Comment by WorksButNotTested** [comment]
[This](https://frida.re/docs/hacking/) is the guide I follow. Sometimes I have to tweak a few things in releng/setup-env.sh for embedded targets to modify things like meson_host_cpu, host_arch_flags or host_toolprefix for example, but for mainstream Linux you will probably be ok.

If you want to build the SDK from source (rather than have frida download one automatically assuming it has been cached by the CI stuff upstream) try:

make -f Makefile.sdk.mk FRIDA_HOST=linux-arm64

If you just type make in the top-level repo you will then get a list of targets. I think you will most likely want:
make gum-linux-arm64
make core-linux-arm64

**Comment by WorksButNotTested** [comment]
If you head on over to the telegram channel [here](https://telegram.me/fridadotre), people should be able to help you out.

**Comment by vanhauser-thc** [comment]
@WorksButNotTested  thanks a lot!
A pointer in the README here to https://frida.re/docs/hacking/ would help.
I am just interested (or better: I only need) frida-gum and have not used frida before so I wasnt aware that the build instructions are in a different repo :)
